import '@coinbase/onchainkit/styles.css';
import type { Metadata } from 'next';
import './globals.css';
import { WagmiProvider } from './providers';
import { ThemeProvider } from './theme-provider';
import { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME,
  description: 'Generated by `create-onchain`, a Next.js template for OnchainKit',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
      </head>
      <body className="bg-background">
        <ThemeProvider>
          <WagmiProvider>
            <Toaster position="top-right" />
            {children}
          </WagmiProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
